/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Product;
import model.ProductHistory;

/**
 *
 * @author ruthwiksoudry
 */
public class ViewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJPanel
     */
    
    ProductHistory history;
    
    public ViewJPanel(ProductHistory history) {
        initComponents();
        
        this.history=history;
        populateRecordTable();
//        displayProduct();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtWarrentyYear = new javax.swing.JTextField();
        lblOwnerEmailAddress = new javax.swing.JLabel();
        txtEngineNo = new javax.swing.JTextField();
        lblOwnerSocialSecurityNo = new javax.swing.JLabel();
        lblLicensePlates = new javax.swing.JLabel();
        lblServiceRecords = new javax.swing.JLabel();
        txtOwnerTelephoneNo = new javax.swing.JTextField();
        txtOwnerName = new javax.swing.JTextField();
        txtSeatsNo = new javax.swing.JTextField();
        txtColor = new javax.swing.JTextField();
        txtOwnerAddress = new javax.swing.JTextField();
        lblEngineNo = new javax.swing.JLabel();
        txtOwnerSocialSecurityNo = new javax.swing.JTextField();
        lblTelephoneNo = new javax.swing.JLabel();
        lblOwnerName = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        txtOwnerDriverLiscence = new javax.swing.JTextField();
        txtServiceRecord = new javax.swing.JTextField();
        lblWarrentyYear = new javax.swing.JLabel();
        txtOwnerEmailAddress = new javax.swing.JTextField();
        lblOwnerAddress = new javax.swing.JLabel();
        txtLicensePlates = new javax.swing.JTextField();
        lblOwnerDriverLiscence = new javax.swing.JLabel();
        lblColor = new javax.swing.JLabel();
        lblSeatsNo = new javax.swing.JLabel();
        lblYear = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        lblView = new javax.swing.JLabel();
        lblBrand = new javax.swing.JLabel();
        lblModel = new javax.swing.JLabel();
        txtYear = new javax.swing.JTextField();
        txtModel = new javax.swing.JTextField();
        lblViewServiceRecords = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblServiceRecord = new javax.swing.JTable();
        btnRecordDelete = new javax.swing.JButton();
        lblViewImg = new javax.swing.JLabel();

        txtWarrentyYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWarrentyYearActionPerformed(evt);
            }
        });

        lblOwnerEmailAddress.setText("Owner Email Address:");

        txtEngineNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEngineNoActionPerformed(evt);
            }
        });

        lblOwnerSocialSecurityNo.setText("Owner Social Security No:");

        lblLicensePlates.setText("License Plate:");

        lblServiceRecords.setText("Service Records:");

        txtOwnerTelephoneNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOwnerTelephoneNoActionPerformed(evt);
            }
        });

        txtOwnerName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOwnerNameActionPerformed(evt);
            }
        });

        txtSeatsNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSeatsNoActionPerformed(evt);
            }
        });

        txtColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtColorActionPerformed(evt);
            }
        });

        txtOwnerAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOwnerAddressActionPerformed(evt);
            }
        });

        lblEngineNo.setText("Engine Number:");

        txtOwnerSocialSecurityNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOwnerSocialSecurityNoActionPerformed(evt);
            }
        });

        lblTelephoneNo.setText("Owner Telephone No:");

        lblOwnerName.setText("Owner Name:");

        txtBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBrandActionPerformed(evt);
            }
        });

        txtOwnerDriverLiscence.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOwnerDriverLiscenceActionPerformed(evt);
            }
        });

        txtServiceRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtServiceRecordActionPerformed(evt);
            }
        });

        lblWarrentyYear.setText("Warrenty Year:");

        txtOwnerEmailAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOwnerEmailAddressActionPerformed(evt);
            }
        });

        lblOwnerAddress.setText("Owner Address:");

        txtLicensePlates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLicensePlatesActionPerformed(evt);
            }
        });

        lblOwnerDriverLiscence.setText("Owner Driver Liscence:");

        lblColor.setText("Color:");

        lblSeatsNo.setText("Seats Number:");

        lblYear.setText("Year:");

        lblPhoto.setText("Photo:");

        lblView.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        lblView.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblView.setText("View Car");

        lblBrand.setText("Brand:");

        lblModel.setText("Model:");

        txtYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYearActionPerformed(evt);
            }
        });

        txtModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtModelActionPerformed(evt);
            }
        });

        lblViewServiceRecords.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        lblViewServiceRecords.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblViewServiceRecords.setText("View Service Records");

        tblServiceRecord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Service Date", "Service Estimate", "Service Company"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblServiceRecord);

        btnRecordDelete.setText("Delete");
        btnRecordDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblViewServiceRecords, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRecordDelete)
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblViewImg, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblOwnerSocialSecurityNo)
                                .addGap(59, 59, 59)
                                .addComponent(txtOwnerSocialSecurityNo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblServiceRecords)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtServiceRecord, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lblOwnerAddress)
                                                        .addGap(115, 115, 115)
                                                        .addComponent(txtOwnerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(lblWarrentyYear)
                                                        .addGap(124, 124, 124)
                                                        .addComponent(txtWarrentyYear, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(10, 10, 10))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblPhoto)
                                                .addGap(58, 58, 58)))))))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(lblBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(114, 114, 114)
                            .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(lblModel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(111, 111, 111)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(lblColor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(111, 111, 111)
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(lblYear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(111, 111, 111)
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(lblEngineNo)
                            .addGap(111, 111, 111)
                            .addComponent(txtEngineNo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(lblSeatsNo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(111, 111, 111)
                            .addComponent(txtSeatsNo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(lblOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(111, 111, 111)
                            .addComponent(txtOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(lblTelephoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(111, 111, 111)
                            .addComponent(txtOwnerTelephoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(lblOwnerEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(111, 111, 111)
                            .addComponent(txtOwnerEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(lblOwnerDriverLiscence, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(111, 111, 111)
                            .addComponent(txtOwnerDriverLiscence, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(lblView, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addComponent(lblLicensePlates, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(111, 111, 111)
                            .addComponent(txtLicensePlates, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblView)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(lblBrand))
                            .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblModel)
                            .addComponent(txtModel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblColor)
                            .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblYear)
                            .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lblEngineNo))
                            .addComponent(txtEngineNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lblSeatsNo))
                            .addComponent(txtSeatsNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLicensePlates)
                            .addComponent(txtLicensePlates, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblOwnerName))
                            .addComponent(txtOwnerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lblTelephoneNo))
                            .addComponent(txtOwnerTelephoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblOwnerEmailAddress))
                            .addComponent(txtOwnerEmailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lblOwnerDriverLiscence))
                            .addComponent(txtOwnerDriverLiscence, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblOwnerSocialSecurityNo))
                            .addComponent(txtOwnerSocialSecurityNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblOwnerAddress)
                        .addGap(18, 18, 18)
                        .addComponent(lblServiceRecords))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtOwnerAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtServiceRecord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWarrentyYear)
                    .addComponent(txtWarrentyYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(lblPhoto)
                .addGap(7, 7, 7)
                .addComponent(lblViewImg, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 176, Short.MAX_VALUE)
                .addComponent(lblViewServiceRecords)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRecordDelete)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtWarrentyYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWarrentyYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWarrentyYearActionPerformed

    private void txtEngineNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEngineNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEngineNoActionPerformed

    private void txtOwnerTelephoneNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOwnerTelephoneNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOwnerTelephoneNoActionPerformed

    private void txtOwnerNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOwnerNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOwnerNameActionPerformed

    private void txtSeatsNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSeatsNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSeatsNoActionPerformed

    private void txtColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtColorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtColorActionPerformed

    private void txtOwnerAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOwnerAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOwnerAddressActionPerformed

    private void txtOwnerSocialSecurityNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOwnerSocialSecurityNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOwnerSocialSecurityNoActionPerformed

    private void txtBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBrandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBrandActionPerformed

    private void txtOwnerDriverLiscenceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOwnerDriverLiscenceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOwnerDriverLiscenceActionPerformed

    private void txtServiceRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtServiceRecordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtServiceRecordActionPerformed

    private void txtOwnerEmailAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOwnerEmailAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOwnerEmailAddressActionPerformed

    private void txtLicensePlatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLicensePlatesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLicensePlatesActionPerformed

    private void txtYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYearActionPerformed

    private void txtModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtModelActionPerformed

    private void btnRecordDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblServiceRecord.getSelectedRow();
        
        if(selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a row to delete");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblServiceRecord.getModel();
        Product selectedProduct = (Product) model.getValueAt(selectedRowIndex, 0);
        
        history.deleteProduct(selectedProduct);
        
        JOptionPane.showMessageDialog(this, "Product Car Deleted");
        
        populateRecordTable();
        
    }//GEN-LAST:event_btnRecordDeleteActionPerformed

//     private void displayProduct() {                                         
//        // TODO add your handling code here:
//        txtBrand.setText(product.getBrand());
//        txtModel.setText(product.getModel());
//        txtColor.setText(product.getColor());
//        txtYear.setText(product.getYear());
//        txtEngineNo.setText(product.getEngineNo());
//        txtSeatsNo.setText(product.getSeatsNo());
//        txtLicensePlates.setText(product.getLicensePlates());
//        txtOwnerName.setText(product.getOwnerName());
//        txtOwnerTelephoneNo.setText(product.getOwnerTelephoneNo());
//        txtOwnerDriverLiscence.setText(product.getOwnerDriverLicense());
//        txtOwnerAddress.setText(product.getOwnerAddress());
//        txtOwnerEmailAddress.setText(product.getOwnerEmailAddresses());
//        txtOwnerSocialSecurityNo.setText(product.getOwnerSocialSecurityNo());
//        txtServiceRecord.setText(product.getServiceRecords());
//        txtWarrentyYear.setText(product.getWarrantyYear());
//        txtPhoto.setText(product.getPhoto());
//        
//    }                                        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRecordDelete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBrand;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblEngineNo;
    private javax.swing.JLabel lblLicensePlates;
    private javax.swing.JLabel lblModel;
    private javax.swing.JLabel lblOwnerAddress;
    private javax.swing.JLabel lblOwnerDriverLiscence;
    private javax.swing.JLabel lblOwnerEmailAddress;
    private javax.swing.JLabel lblOwnerName;
    private javax.swing.JLabel lblOwnerSocialSecurityNo;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblSeatsNo;
    private javax.swing.JLabel lblServiceRecords;
    private javax.swing.JLabel lblTelephoneNo;
    private javax.swing.JLabel lblView;
    private javax.swing.JLabel lblViewImg;
    private javax.swing.JLabel lblViewServiceRecords;
    private javax.swing.JLabel lblWarrentyYear;
    private javax.swing.JLabel lblYear;
    private javax.swing.JTable tblServiceRecord;
    private javax.swing.JTextField txtBrand;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtEngineNo;
    private javax.swing.JTextField txtLicensePlates;
    private javax.swing.JTextField txtModel;
    private javax.swing.JTextField txtOwnerAddress;
    private javax.swing.JTextField txtOwnerDriverLiscence;
    private javax.swing.JTextField txtOwnerEmailAddress;
    private javax.swing.JTextField txtOwnerName;
    private javax.swing.JTextField txtOwnerSocialSecurityNo;
    private javax.swing.JTextField txtOwnerTelephoneNo;
    private javax.swing.JTextField txtSeatsNo;
    private javax.swing.JTextField txtServiceRecord;
    private javax.swing.JTextField txtWarrentyYear;
    private javax.swing.JTextField txtYear;
    // End of variables declaration//GEN-END:variables

    private void populateRecordTable () {
        DefaultTableModel model = (DefaultTableModel) tblServiceRecord.getModel();
        model.setRowCount(0);
        
        for(Product prod : history.getHistory()) {
            Object[] row = new Object[3];
            row[0] = prod.getServiceDate();
            row[1] = prod.getServiceEstimate();
            row[2] = prod.getServiceCompany();
            
            model.addRow(row);
            
        txtBrand.setText(prod.getBrand());
        txtModel.setText(String.valueOf(prod.getModel()));
        txtColor.setText(prod.getColor());
//        txtYear.setText(String.valueOf(prod.getYear()));
        txtEngineNo.setText(String.valueOf(prod.getEngineNo()));
        txtSeatsNo.setText(String.valueOf(prod.getSeatsNo()));
        txtLicensePlates.setText(prod.getLicensePlates());
        txtOwnerName.setText(prod.getOwnerName());
        txtOwnerTelephoneNo.setText(prod.getOwnerTelephoneNo());
        txtOwnerDriverLiscence.setText(prod.getOwnerDriverLicense());
        txtOwnerAddress.setText(prod.getOwnerAddress());
        txtOwnerEmailAddress.setText(prod.getOwnerEmailAddresses());
        txtOwnerSocialSecurityNo.setText(prod.getOwnerSocialSecurityNo());
        txtServiceRecord.setText(prod.getServiceRecords());
        txtWarrentyYear.setText(String.valueOf(prod.getWarrantyYear()));
//        lblImageView.setIcon((new ImageIcon(prod.getPhoto())));
        lblViewImg.setIcon(new ImageIcon(prod.getPhoto()));
        }
    }
    
}
